version: "2.2"

services:

  blink:
    container_name: blink_app
    image: node:9.4.0-alpine
    init: true
    env_file: .env
    # depends_on: 
    #   - redis
    labels:
      blink.maintainer: "sado.ogie@gmail.com"
      blink.description: "The blink takeover"
      blink.version: "1.0"
    user: node
    working_dir: /home/node/blink
    expose:
      - "80"
    volumes:
      - "./:/home/node/blink"
      - "storage:/storage"
    networks: 
      network:
        aliases:
          - blink
    command: ./start.sh
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3080"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://192.168.0.42:123"

  nginx:
    container_name: blink_nginx
    image: nginx:1.13.8-alpine
    ports:
      - "3080:80"
    networks: 
        network:
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks: 
  network:

volumes:
  storage:
