version: "2.2"

services:

  blink:
    container_name: blink_app
    image: node:9.4.0-alpine
    init: true
    env_file: .env
    depends_on: 
      - redis
    labels:
      blink.maintainer: "sado.ogie@gmail.com"
      blink.description: "The blink takeover"
      blink.version: "1.0"
    user: node
    working_dir: /home/node/blink
    expose:
      - "8080"
    volumes:
      - "./:/home/node/blink"
      - "storage:/storage"
    networks: 
      network:
        aliases:
          - blink-app #note you can resolve conatainers by their service name like http://blink instead of the alias
    command: ./start.sh
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3080"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://192.168.0.42:123"

  nginx:
    container_name: blink_nginx
    image: nginx:1.13.8-alpine
    depends_on: 
      - blink
    ports:
      - "3080:80"
    networks: 
      network:
        aliases:
          - blink-nginx
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    container_name: blink_redis
    image: redis:4.0.7-alpine
    expose: 
      - "6379"
    env_file: .env
    volumes: 
      - ./storage/redis:/data:rw
    networks:
      network:
        aliases:
          - blink-redis
    command: redis-server --appendonly yes

networks: 
  network: 

volumes:
  storage:
