version: "2.3"

services:

  blink:
    container_name: ${APP_NAME}_app
    image: node:${NODE_VERSION}-alpine
    init: true
    env_file: .env
    depends_on: 
      - redis
      - elasticsearch
    labels:
      blink.maintainer: ${APP_MAINTAINER}
      blink.description: ${APP_DESCRIPTION}
      blink.version: ${APP_VERSION}
    user: node
    working_dir: /home/node/blink
    expose:
      - ${NODE_PORT}
    volumes:
      - "./:/home/node/blink"
      - "storage:/storage"
    networks: 
      network:
        aliases:
          - ${APP_NAME}-app
    command: ./start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NODE_PORT}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: ${NODE_LOG_DRIVER}
      options:
        max-size: ${NODE_LOG_MAX_SIZE}
        max-file: ${NODE_LOG_MAX_FILES}

  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:${NGINX_VERSION}-alpine
    depends_on: 
      - blink
    ports:
      - "${APP_PORT}:${NGINX_PORT}"
    networks: 
      network:
        aliases:
          - ${APP_NAME}-nginx
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    container_name: ${APP_NAME}_redis
    image: redis:${REDIS_VERSION}-alpine
    expose: 
      - "${REDIS_PORT}"
    env_file: .env
    volumes: 
      - ./storage/redis:/data:rw
    networks:
      network:
        aliases:
          - ${APP_NAME}-redis
    command: redis-server --appendonly yes

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_SEARCH_VERSION}
    container_name: ${APP_NAME}_elasticsearch
    environment:
      - cluster.name=${APP_NAME}-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./storage/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_SEARCH_PORT}:${ELASTIC_SEARCH_PORT}
    networks:
      network:
        aliases:
          - ${APP_NAME}-elasticsearch

networks: 
  network: 

volumes:
  storage:
